### PR TITLE
fix: custom CSS properties

### LINKED ISSUE #1107: CSS custom properties not properly compiled
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [X] Angular
- [X] HTML
- [X] Qwik
- [X] React
- [X] React-Native
- [ ] Solid
- [X] Stencil
- [X] Svelte
- [X] Vue
- [X] Web components

### Reproduction case

[link](https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNrrgXzgDMoIQ4ByAAQCNlgAbAE3SgDpgIB6EYHVYKgoBuAFCj0AD0iw4LIgENkDeEWQA7AMYxO6uAFkAngGEykdenUwAFGFJhUASkSi4cKOhjIoe667dwADxMwABu%2FgFwmqioALwICBGRlAC0KTDoqDApmhAM0BQAXJQ0DMjoFAA0SZG5%2BVDFFKEKUNZpGVk5edCV7uhMjlU1BPhJAHyBXCGhY%2F6OYqNAA%3D)

### Expected Behaviour

The CSS from an element that contains a custom property (CSS variable) like below:

```jsx
<div css={{
  '--test-color': 'blue',
  color: "var(--test-color, red)",
}}></div>
```

should compile to valid CSS like in the following example:

```html
<style>
  .div {
    --test-color: blue;
    color: var(--test-color, red);
  }
</style>
```

### Actual Behaviour

The CSS from an element that contains a custom property (CSS variable) like below:

```jsx
<div css={{
  '--test-color': 'blue',
  color: "var(--test-color, red)",
}}></div>
```

compiles to the following (the `--` part from the CSS custom property is omitted):

```html
<style>
  .div {
    test-color: blue;
    color: var(--test-color, red);
  }
</style>
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ohkimur**
## Description

Add a short description of:
I added a function to parse CSS keys that cover the edge case where a custom CSS property is present. This function will also allow for covering other edge cases in the future if it's the case.

This PR closes #1107

### CODE REVIEW

**Comment by ohkimur** [comment]
@illustrofia This should fix our issues.

**Comment by ohkimur** [comment]
@samijaber Do you have a process for merging the PRs? I would like to contribute more, and I would like to know how I can do a better job.

**Review by samijaber — COMMENTED** [review]
Awesome, thanks! Can you add an example in the snapshot tests? You can reuse this test here:

https://github.com/BuilderIO/mitosis/blob/26a4f4ffdaef0f0001038ed5adbb7f0669a832e8/packages/core/src/__tests__/data/nested-styles.raw.tsx#L5-L6

by updating the `foo` line to something like:

```
        '--bar': 'red',
        color: 'var(--bar)',
```

and then run `yarn snapupdate` in `packages/core` to generate new snapshots.

**Comment by ohkimur** [comment]
@samijaber I updated the `nested-styles.ray.tsx` file.

**Review by samijaber — APPROVED** [review]
Thanks! 🚀

**Pull request merged**
