### PR TITLE
fix: wrap mobx react components with state in an observer

### LINKED ISSUE #794: useLocalObservable needs an Observer wrapper in the jsx
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [X] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKMCGN0A0KG206cAvnAGZQQhwBEAAgEbLAA2AJulAHTAIAehDAYEVMFSMA3ACh56AB6RYcXtRzJO8asgB2AYxhCDcALIBPAML1IB9AZgAKMHTCoAlInlw4RhAGqPAheOQAvMRYElDoLgh%2B%2FjQQEABcTKw4UIxJFF6K%2FnEwyFDmLkn%2BADzcwABuAHyVyVXABmDIMM3JAaioEQiJPcMBEJzQGYxx3IwE3ckUFPPCTSMAEuic4wCEcACSATjmUIZwbXAASug4JkQAasiEcJhjwNxE0HAAMsAAjhzcbbNKrCWqNJJeBQUIA%3D%3D

### Expected Behaviour

The component should be wrapped in an `observer` or the jsx content should be wrapped in an `Observer` .

```
const MyComponent = observer(() => (props: any) {
  const state = useLocalObservable(() => ({ foo: "bar" }));

  return (
    <>
      <div>
        <input className="input" />
        Hello! I can run in React, Vue, Solid, or Liquid!
      </div>
    </>
  );
});

export default MyComponent;
```

OR

```
  return (
    <Observer>
      {() => (
        <div>
          <input className="input" />
          Hello! I can run in React, Vue, Solid, or Liquid!
        </div>
      )}
    </Observer>
  );
```

### Actual Behaviour

There is no `observer` or `Observer`. This means that the component does not rerender when the `localObservableState` changes

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by cmgriffing**
## Description

This relates to Issue 794: https://github.com/BuilderIO/mitosis/issues/794

I added a snapshot test at the very least.
I don't think we have enough tests to catch regressions for all the edge cases such as when there is a `forwardRef`. I might have missed it though.

I did however functionally test it in a local project after monkey-patching the generator file with my modified code. Worked just fine.

I'm happy to make any changes needed.

example output: 

```typescript
import * as React from "react";
import { useLocalObservable, observer } from "mobx-react-lite";
import { generateData, SIZE } from "./avatar-beam.utils";

function AvatarBeam(props: any) {
  const state = useLocalObservable(() => ({
    get data() {
      return generateData(props.name, props.colors);
    },
  }));

  return (
    <svg
      fill="none"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewBox={"0 0 " + SIZE + " " + SIZE}
      width={props.size}
      height={props.size}
    >
      {props.title ? <title>{props.name}</title> : null}

      <mask
        id="mask__beam"
        maskUnits="userSpaceOnUse"
        x={0}
        y={0}
        width={SIZE}
        height={SIZE}
      >
        <rect
          fill="#FFFFFF"
          width={SIZE}
          height={SIZE}
          rx={props.square ? undefined : SIZE * 2}
        />
      </mask>

      <g mask="url(#mask__beam)">
        <rect width={SIZE} height={SIZE} fill={state.data.backgroundColor} />

        <rect
          x="0"
          y="0"
          width={SIZE}
          height={SIZE}
          transform={
            "translate(" +
            state.data.wrapperTranslateX +
            " " +
            state.data.wrapperTranslateY +
            ") rotate(" +
            state.data.wrapperRotate +
            " " +
            SIZE / 2 +
            " " +
            SIZE / 2 +
            ") scale(" +
            state.data.wrapperScale +
            ")"
          }
          fill={state.data.wrapperColor}
          rx={state.data.isCircle ? SIZE : SIZE / 6}
        />

        <g
          transform={
            "translate(" +
            state.data.faceTranslateX +
            " " +
            state.data.faceTranslateY +
            ") rotate(" +
            state.data.faceRotate +
            " " +
            SIZE / 2 +
            " " +
            SIZE / 2 +
            ")"
          }
        >
          {state.data.isMouthOpen ? (
            <path
              fill="none"
              strokeLinecap="round"
              d={"M15 " + (19 + state.data.mouthSpread) + "c2 1 4 1 6 0"}
              stroke={state.data.faceColor}
            />
          ) : (
            <path
              d={"M13," + (19 + state.data.mouthSpread) + " a1,0.75 0 0,0 10,0"}
              fill={state.data.faceColor}
            />
          )}

          <rect
            stroke="none"
            x={14 - state.data.eyeSpread}
            y={14}
            width={1.5}
            height={2}
            rx={1}
            fill={state.data.faceColor}
          />

          <rect
            stroke="none"
            x={20 + state.data.eyeSpread}
            y={14}
            width={1.5}
            height={2}
            rx={1}
            fill={state.data.faceColor}
          />
        </g>
      </g>
    </svg>
  );
}

const observedAvatarBeam = observer(AvatarBeam);
export default observedAvatarBeam;

```

fixes #794

### CODE REVIEW

**Comment by cmgriffing** [comment]
I fixed the merge conflict. The section modified to handle the component declaration is getting a bit hairy.

Would it make sense to refactor it to a utility function?

**Comment by samijaber** [comment]
@cmgriffing I think you need to rerun `yarn snapupdate` to generate the new test snapshots. They went away

**Comment by cmgriffing** [comment]
Ah my mistake. I will do that asap.

**Comment by cmgriffing** [comment]
I remembered what happened. I had a merge conflict and just blew away my changes to make the merge simpler.

I have updated the snapshots.

**Comment by samijaber** [comment]
@cmgriffing seems like they're still failing with some mismatched snapshots 🤔

**Comment by samijaber** [comment]
Thanks a lot for you first contribution @cmgriffing !!

**Comment by cmgriffing** [comment]
Thanks. I realized I was just running the core tests. Not the whole tests. Going back and seeing the contributing doc again, its clearly mentioned to use the ci command, so I just missed that. Sorry.

**Comment by samijaber** [comment]
No worries at all! Had to make some minor adjustments to the test, was easier to do it for ya

**Pull request merged**
