### PR TITLE
css fix

### PR DESCRIPTION
**Pull request by Lokprakash-babu**
## CSS fix for autocomplete styles in light mode [issue](https://github.com/BuilderIO/mitosis/issues/1035)

Add a short description of:
- Changed the text color based on the theme. 
- Previously, text color was targeted globally through a>span. Seems like Monaco autocomplete uses same DOM structure for texts inside autocomplete. 
- With old CSS structure for styling the code, it might affect globally wherever we are using 'a' tags. Since, the text is white color using it with white background might not be intuitive. Hence moved the css which targets color to the header link.

### CODE REVIEW

**Review by ohkimur — APPROVED** [review]

**Comment by samijaber** [comment]
Awesome! Thank you for taking a stab at this 🙏🏽 


I think there is still 1 place missing where the CSS needs to be changed: the color of some of the text is still `black` even though it should be `white`. 

See this  screenshot: 


CleanShot 2023-04-18 at 11 05 42@2x

**Comment by Lokprakash-babu** [comment]
@samijaber Please check now. Fixed this in the latest commit.

**Review by samijaber — APPROVED** [review]
Wonderful, thank you for fixing this!

**Comment by samijaber** [comment]
@Lokprakash-babu you need to lint your PR with `yarn run lint` at the root of the repo

**Pull request merged**
