### PR TITLE
fix(vue): add this prefix methods for options API #780

### PR DESCRIPTION
**Pull request by jcfauchet**
## Description

Fix of the issue [780](https://github.com/BuilderIO/mitosis/issues/780)

### CODE REVIEW

**Review by raymondmuller — APPROVED** [review]
Nice!

**Comment by steve8708** [comment]
great to see you in our PRs @jcfauchet!

**Comment by jcfauchet** [comment]
> great to see you in our PRs @jcfauchet!

Thank you @steve8708 :)

**Comment by jcfauchet** [comment]
> Welcome to Mitosis @jcfauchet 🙏🏽 

Thx @samijaber :)

**Pull request merged**
