### PR TITLE
chore: add feature request template

### PR DESCRIPTION
**Pull request by kingzez**
## Description

Add a short description of:
- what changes you made: add feature request tempalte
- why you made them: help us to get a good start for feature request

It look like 

---

image

### CODE REVIEW

**Comment by ohkimur** [comment]
@kingzez I find this very useful.

**Review by samijaber — APPROVED** [review]
Good idea!

**Comment by samijaber** [comment]
No idea why this PR is failing... 🤨

**Comment by kingzez** [comment]
so strange

**Comment by ohkimur** [comment]
@kingzez Maybe you should just create another PR.

**Review by PatrickJS — APPROVED** [review]

**Comment by PatrickJS** [comment]
the error@samijaber 
https://github.com/BuilderIO/mitosis/actions/runs/4825669240/jobs/8596874836#step:7:398
`[vite] Internal server error: Failed to resolve entry for package "@e2e-app/qwik". The package may have incorrect main/module/exports specified in its package.json.`

**Comment by samijaber** [comment]
superseded by #1193

**Pull request closed without merging**
