### PR TITLE
feat(core): add sveltosis as an official svelte parser for Mitosis

### PR DESCRIPTION
**Pull request by raymondmuller**
## Description

Adding https://sveltosis.dev, a Svelte parser for Mitosis to this repo. 🥳

### CODE REVIEW

**Comment by samijaber** [comment]
@raymondmuller added your templates as snapshot tests.

I can't load the fiddle though due to the `svelte-preprocess` dependency in  `parseSvelte`
CleanShot 2022-11-11 at 15 27 21@2x

Any ideas? How did you work around this in the other fiddle?

**Comment by raymondmuller** [comment]
> @raymondmuller added your templates as snapshot tests.
> 
> I can't load the fiddle though due to the `svelte-preprocess` dependency in  `parseSvelte`
> CleanShot 2022-11-11 at 15 27 21@2x
> 
> Any ideas? How did you work around this in the other fiddle?

Awesome! In the Sveltosis repo I did this:

https://github.com/sveltosis/sveltosis/blob/main/packages/fiddle/next.config.js#L18

Also ignored another one just below that.

**Comment by samijaber** [comment]
Thanks for that, it helped (a bit).

Getting some problems now around `svelte-reprocess` importing CJS code that has `module.exports` syntax in it I think: 
CleanShot 2022-11-11 at 16 44 38@2x

🤔

**Comment by raymondmuller** [comment]
> Thanks for that, it helped (a bit).
> 
> Getting some problems now around `svelte-reprocess` importing CJS code that has `module.exports` syntax in it I think: CleanShot 2022-11-11 at 16 44 38@2x
> 
> 🤔

Look at this :) https://github.com/sveltosis/sveltosis/blob/main/packages/parser/package.json#L50

**Comment by raymondmuller** [comment]
Fiddle should work now!

https://user-images.githubusercontent.com/3808818/201445456-eb58417a-8bd6-49e4-957c-16b1899c7903.mov

**Review by samijaber — APPROVED** [review]
😎

**Pull request merged**
