### PR TITLE
Change to make note of {} control

### PR DESCRIPTION
**Pull request by SupaSibs**
In Mitosis you can use {} inside of a return to use a loop or a conditional statement. But the docs only said that you can use the <Show> and <For> elements.

### CODE REVIEW

**Comment by tomByrer** [comment]
Might want to add tests to prove this works for all targets.

**Comment by SupaSibs** [comment]
Conditional statements are working on all except for HTML and Liquid. However I found a bug on Webcomponents which i think can be fixed: the conditional statement only runs after the values are changed more than once. This is the same for the loops but I haven't finished testing that's why I haven't sent results on it.

**Comment by SupaSibs** [comment]
If I find any more issues I can fix I might close this and open up an issue instead. Unless the {} functionallity is unintended, then I'll just close the pr.

**Comment by SupaSibs** [comment]
As for for loops using {}, it doesn't work on WebComponents and HTMK

**Comment by SupaSibs** [comment]
I cant read swift tho and I dont have an environment so I dont know if it works there.

**Comment by SupaSibs** [comment]
And what's worth noting is that show and for dont work on Webcomps and HTML either, not just {}. Perhaps i'll make an issue on that later?

**Pull request closed without merging**
