### PR TITLE
Fix/529 add TS support to fiddle

### PR DESCRIPTION
**Pull request by raymondmuller**
## Description

Adds Typescript support to fiddle (solves #529).

Screenshot 2022-08-25 at 23 19 08

Screenshot 2022-08-25 at 23 18 22

Screenshot 2022-08-25 at 23 19 22

Also replaces createMuiTheme with createTheme per the deprecation notice in the console and updates **next**.

### CODE REVIEW

**Comment by raymondmuller** [comment]
Not sure why the build fails saying it can't find the types import @samijaber  . Works fine for me locally (running yarn ci:fiddle-build).

**Comment by samijaber** [comment]
> Not sure why the build fails saying it can't find the types import @samijaber . Works fine for me locally (running yarn ci:fiddle-build).

I assume that's because the path to the node modules is different in the Vercel server itself. 🤔

Maybe we should look at https://webpack.js.org/guides/asset-modules/ instead: seems like a replacement for the raw-loader, and maybe that will work better 🤔

**Comment by raymondmuller** [comment]
@samijaber 
JsxRuntimeTypes is found (@builder.io/mitosis/jsx-runtime) however the other types aren't. I've added index.d.ts to the exports in package.json, but that didn't seem to help either (https://github.com/BuilderIO/mitosis/pull/668/files#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7R35). Is this cached and does the dependency (mitosis in this case) need to be updated? 

I see this in the GH Action (  ➤ YN0013: │ 2490 packages were already cached)

**Review by samijaber — APPROVED** [review]
🏆 🏆 🏆 🏆

**Pull request merged**
