### PR TITLE
feat: add flutter support

### PR DESCRIPTION
**Pull request by omariosouto**
## Description

Add a short description of:
- what changes you made, 
- why you made them, and 
- any other context that you think might be helpful for someone to better understand what is contained in this pull request. 

This sort of information is useful for people reviewing the code, as well as anyone from the future trying to understand why changes were made or why a bug started happening.

### CODE REVIEW

**Comment by samijaber** [comment]
But Mitosis doesn't have any support for flutter...?

**Comment by PatrickJS** [comment]
maybe this means we should add it or maybe he is working on it

**Comment by omariosouto** [comment]
Hey folks, sorry! the idea was to open in my fork sdhuadhuasuh my bad I'm working on it!

**Comment by omariosouto** [comment]
This project was something like what you are doing here: https://github.com/skynexui/components

I was creating a compatibility layer between Flutter and React.

**Comment by nhensh** [comment]
Would love flutter support at the moment I'm using the React Native target and using [this tool](https://github.com/GeekyAnts/react-native-to-flutter) to convert it - https://github.com/GeekyAnts/react-native-to-flutter

**Pull request closed without merging**
