### PR TITLE
chore: replace traverse for neotraverse

### PR DESCRIPTION
**Pull request by max-arias**
## Description

Please provide the following information:

- What changes you made: 
  - Replaces `traverse` for `neotraverse`

- Why you made them, and: 
  - Replaces `traverse` for `neotraverse` to avoid unnecessary extra deps from you-know-who, uses the "legacy" import to avoid having to rewrite any code.

- Any other useful context: 
  - (I'm not the author) https://puruvj.dev/blog/forking-and-fixing-traverse

Make sure to follow the PR preparation steps in [CONTRIBUTING.md](../CONTRIBUTING.md#preparing-your-pr) before submitting your PR:

- [x] format the codebase: from the root, run `yarn fmt:prettier`.
- [x] update all snapshots (in core & CLI): from the root, run `yarn test:update`
- [x] add Changeset entry: from the root, run `yarn g:changeset` and follow the CLI instructions. Alternatively, use the Changeset Github Bot to create the file.

### CODE REVIEW

**Comment by PuruVJ** [comment]
Hi, creator of neotraverse here. I wanna ask whether there were any issues with neotraverse such that it couldn't be merged? 😄

**Comment by max-arias** [comment]
> Hi, creator of neotraverse here. I wanna ask whether there were any issues with neotraverse such that it couldn't be merged? 😄

Hey, ended up running into some issues with tests. Didn't look much into it, but since Im not a maintainer pushing for a dependency update (and most likely fixing some tests) felt like something it doesnt need now.

Appreciate the effort of neotraverse though, it was plug and play

**Comment by samijaber** [comment]
@max-arias I was actually curious to try this out when I saw @PuruVJ's announcement about `neotraverse`!

You have my blessing and encouragement to get this PR over the edge 🙏🏽

We have highly extensive snapshot test coverage, so if everything is ✅  we can merge this PR

**Comment by max-arias** [comment]
> @max-arias I was actually curious to try this out when I saw @PuruVJ's announcement about `neotraverse`!
> 
> You have my blessing and encouragement to get this PR over the edge 🙏🏽
> 
> We have highly extensive snapshot test coverage, so if everything is ✅ we can merge this PR

I'll revisit this then, thanks!

**Comment by max-arias** [comment]
> Thanks for reopening!
> 
> Might I suggest importing directly from neotraverse? It's the same all but for node it 18+, so should work ideally

Will do 👍  I was following: https://puruvj.dev/blog/forking-and-fixing-traverse#Legacy-mode that suggests using legacy if there are many instances of traverse in the codebase, I figured it was a backwards compatible version.

**Comment by PuruVJ** [comment]
Even the legacy version doesn’t support node 0.4 though 😅, so it’s still
not 100% backward compatible

Beside that, default build should work as is for modern projects without
having to change how it’s used. Based on what I see, even using
neotraverse/modern will be a pretty small change overall, so that would
work as well

**Comment by samijaber** [comment]
The errors you're hitting are all TS type errors because you removed `@types/traverse`, but `neotraverse/legacy` does not provide types.

I think you'll want to use the regular non-legacy import to be able to get types again.

**Comment by PuruVJ** [comment]
Webpack strikes again. Seems you will have to use `neotraverse/legacy` only. I have got a fix for types in legacy, will publish in a few minutes

**Comment by PuruVJ** [comment]
@max-arias could run `npm i https://pkg.pr.new/PuruVJ/neotraverse@4` and see if everything builds? If it does, I'll cut a 0.6.10 release which can then be installed as final

**Comment by max-arias** [comment]
> @max-arias could you run `yarn add https://pkg.pr.new/PuruVJ/neotraverse@4` and see if everything builds? If it does, I'll cut a 0.6.10 release which can then be installed as final

Bit late and my brain ain't brainin, but no luck with `from 'neotraverse'`:

Screenshot 2024-07-15 203244

No luck with `neotraverse/legacy`:

Screenshot 2024-07-15 203732

`yarn.lock`:

Screenshot 2024-07-15 203839

**Comment by PuruVJ** [comment]
Just published 0.6.10, could you try that? Maybe yarn doesn't play well with pkg.pr.new yet

**Comment by PuruVJ** [comment]
Uhh I figured it out, its related to tsconfig

**Comment by max-arias** [comment]
> Just published 0.6.10, could you try that? Maybe yarn doesn't play well with pkg.pr.new yet

No luck, same errors.

I don't think wsl is the issue, but just in case:

Screenshot 2024-07-15 205154

**Comment by PuruVJ** [comment]
This is a deep can of worms. It can be fixed by changing module: ESNext in tsconfig, but that causes more type errors, namely with svelte/types/interfaces/compiler, as those types dont exist anymore.

Other option is to not type the options object at all for neotraverse. if that's fine we're good to go

**Comment by maxarias-io** [comment]
What do you think @samijaber ?

**Comment by PuruVJ** [comment]
I opened #1500 fixing the different issues

**Pull request closed without merging**
