### PR TITLE
fix: onInit throwing useEffect not defined

### PR DESCRIPTION
**Pull request by chadalen**
## Description
Fixes issue
https://github.com/BuilderIO/mitosis/issues/428

### CODE REVIEW

**Review by PatrickJS — APPROVED** [review]

**Comment by samijaber** [comment]
@chadalen you need to update the jest tests in `packages/core`, by running `yarn run snapupdate`

**Comment by chadalen** [comment]
> @chadalen you need to update the jest tests in `packages/core`, by running `yarn run snapupdate`

Done

**Comment by samijaber** [comment]
@chadalen Looking at the github actions again, it looks like you also need to run prettier! `yarn run fmt:prettier` in the root of the project and you're all set on your first contribution here 😄

**Review by samijaber — APPROVED** [review]

**Comment by samijaber** [comment]
@chadalen Haha please do!! That would be greatly appreciated 🙏🏽

**Comment by samijaber** [comment]
And welcome to the Mitosis contributor club!

**Pull request merged**
