### PR TITLE
feat: add yorkie & lint-staged

### PR DESCRIPTION
**Pull request by PengBoUESTC**
## Description

Add a short description of:
- what changes you made, 
- why you made them, and 
- any other context that you think might be helpful for someone to better understand what is contained in this pull request. 

This sort of information is useful for people reviewing the code, as well as anyone from the future trying to understand why changes were made or why a bug started happening.

### CODE REVIEW

**Comment by samijaber** [comment]
@PengBoUESTC I tried this PR locally, and it didn't work. When I use `git commit -m "test message"` with some changes, nothing happens.

**Comment by PengBoUESTC** [comment]
> @PengBoUESTC I tried this PR locally, and it didn't work. When I use `git commit -m "test message"` with some changes, nothing happens.

did you install yorkie & lint-staged dependencies? if u did,  could U check the dir of  .git/hooks , yorkie shuold have created some hook files in this dir ...

by the way what's your computer system,

**Comment by samijaber** [comment]
> > @PengBoUESTC I tried this PR locally, and it didn't work. When I use `git commit -m "test message"` with some changes, nothing happens.
> 
> did you install yorkie & lint-staged dependencies? if u did, could U check the dir of .git/hooks , yorkie shuold have created some hook files in this dir ...
> 
> by the way what's your computer system,

It does not add hooks in `.git/hooks`. I see that husky no longer autoinstalls https://blog.typicode.com/husky-git-hooks-autoinstall/

my computer system is M1 Mac, macOS v12

**Comment by PengBoUESTC** [comment]
> > > @PengBoUESTC I tried this PR locally, and it didn't work. When I use `git commit -m "test message"` with some changes, nothing happens.
> > 
> > 
> > did you install yorkie & lint-staged dependencies? if u did, could U check the dir of .git/hooks , yorkie shuold have created some hook files in this dir ...
> > by the way what's your computer system,
> 
> It does not add hooks in `.git/hooks`. I see that husky no longer autoinstalls https://blog.typicode.com/husky-git-hooks-autoinstall/
> 
> my computer system is M1 Mac, macOS v12

there is a npm hook `install` in `yorkie`;
It‘s seems like that the `install` hook of `package.json` doesn't work . I know this problem in a `pnpm` project. may be I should solve this problem first ...

**Pull request closed without merging**
