### PR TITLE
feat: dev script for mitosis cli

### PR DESCRIPTION
**Pull request by rgodha24**
The main changes made were in the packages/cli/src/build/dev.ts file and packages/cli/src/commands/dev.ts. 

Basically, it runs something like the "build" command on each file change, only on the files changed.

### CODE REVIEW

**Comment by rgodha24** [comment]
I have not added tests because I'm not very good at writing them. If you could provide me with guidance, that would be great!

**Comment by rgodha24** [comment]
@samijaber anything else I can do to get this pr merged?

**Comment by ohkimur** [comment]
@samijaber Isn't this feature very important? Does it need some more love? I would very much use this feature. Looking more at what it does, I don't think it should be called `dev` but rather it should be a `--watch` flag.

@rgodha24 I guess you closed this issue because it passed a long time with no answer, am I right? Would you care to reopen this issue and refactor it from dev to `--watch`? I'm willing to help if necessary.

**Comment by rgodha24** [comment]
mitosis already has a "--watch" flag, but that's much slower, especially when there's large amounts of files. this only rebuilds the files that are actually changed which is why I called it "dev"

**Comment by ohkimur** [comment]
@rgodha24 I see. Maybe we should try to improve that one instead. What do you think about that?

**Comment by kingzez** [comment]
It would be perfect if we supported incremental build.

**Comment by rgodha24** [comment]
I'd be down to reimplement a pr starting on may 11 (my last ap test 💀).

**Comment by samijaber** [comment]
Apologies for the delay in getting to this PR @rgodha24. This is definitely a very useful feature! And there is currently no `--watch` flag for `mitosis build`, so re-implementing this as `mitosis build --dev` would be very useful indeed. 🙏🏽

If you have any doubts or questions, I would suggest opening a github issue outlining how you plan on doing it so we can go over it there before a PR is put up.

**Pull request closed without merging**
